FROM wordpress:latest
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html
EXPOSE 80
EXPOSE 443
ENV WORDPRESS_DB_HOST=localhost \
    WORDPRESS_DB_NAME=wordpress \
    WORDPRESS_DB_USER=root \
    WORDPRESS_DB_PASSWORD=root \
    WORDPRESS_TABLE_PREFIX=wp_
CMD ["apache2-foreground"]